openapi: "3.1.0"
info:
  title: "pianoman API"
  description: "pianoman API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /sse:
    get:
      description: ""