openapi: "3.1.0"
info:
  title: "pianoman API"
  description: "pianoman API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /midi/devices:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MidiDeviceInfo"
  /midi/sse:
    get:
      description: ""
components:
  schemas:
    MidiDeviceInfo:
      type: "object"
      properties:
        name:
          type: "string"
        vendor:
          type: "string"
        description:
          type: "string"
        version:
          type: "string"
      required:
        - "name"
        - "vendor"
        - "description"
        - "version"