openapi: "3.1.0"
info:
  title: "pianoman API"
  description: "pianoman API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /midi/devices:
    get:
      description: "Endpoint to get a list of all available MIDI devices."
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MidiDeviceInfo"
  /midi/devices/{id}:
    get:
      description: "Endpoint to get information about a specific MIDI device by ID.\
        \ <br> id The ID of the MIDI device."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MidiDeviceInfo"
  /midi/devices/{id}/connect:
    post:
      description: "Endpoint to connect to a specific MIDI device by ID. <br> id The\
        \ ID of the MIDI device to connect to."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /midi/devices/{id}/events:
    get:
      description: "Endpoint used for connecting to and get Server-Sent Events (SSE)\
        \ for MIDI messages from the connected device."
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    MidiDeviceInfo:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        vendor:
          type: "string"
        description:
          type: "string"
        version:
          type: "string"
      required:
        - "id"
        - "name"
        - "vendor"
        - "description"
        - "version"