package net.testiprod.pianoman.app.music

data class MidiTimings(
    val note: Int,
    val startTime: Long,
)

val moonlightSonataNotes = listOf(
    MidiTimings("C#2".toNote().toMidiNumber(), 0),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("G#2".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#2".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("G#2".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("B2".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#2".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#4".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("F#4".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("E4".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("G#3".toNote().toMidiNumber(), 300),
    MidiTimings("C#3".toNote().toMidiNumber(), 300),
    MidiTimings("E3".toNote().toMidiNumber(), 300),
    MidiTimings("D#4".toNote().toMidiNumber(), 300),
)

val chordProgression = listOf(
    MidiTimings("C4".toNote().toMidiNumber(), 0),
    MidiTimings("E4".toNote().toMidiNumber(), 0),
    MidiTimings("G4".toNote().toMidiNumber(), 0),
    MidiTimings("C4".toNote().toMidiNumber(), 1000),
    MidiTimings("E4".toNote().toMidiNumber(), 0),
    MidiTimings("A4".toNote().toMidiNumber(), 0),
    MidiTimings("C5".toNote().toMidiNumber(), 0),
    MidiTimings("F4".toNote().toMidiNumber(), 1000),
    MidiTimings("A4".toNote().toMidiNumber(), 0),
    MidiTimings("C5".toNote().toMidiNumber(), 0),
    MidiTimings("G4".toNote().toMidiNumber(), 1000),
    MidiTimings("B4".toNote().toMidiNumber(), 0),
    MidiTimings("D5".toNote().toMidiNumber(), 0),
)